export const tiposPorColor = {
    normal: '#9CA3AF',
    fighting: '#DC2626',
    flying: '#93C5FD',
    poison: '#A78BFA',
    ground: '#B45309',
    rock: '#4B5563',
    bug: '#22C55E',
    ghost: '#4F46E5',
    steel: '#6B7280',
    fire: '#EF4444',
    water: '#3B82F6',
    grass: '#22C55E',
    electric: '#FACC15',
    psychic: '#8B5CF6',
    ice: '#BFDBFE',
    dragon: '#6366F1',
    dark: '#1F2937',
    fairy: '#F9A8D4',
    shadow: '#000000',
};

export const tiposTraducidos = {
    normal: 'Normal',
    fighting: 'Lucha',
    flying: 'Volador',
    poison: 'Veneno',
    ground: 'Tierra',
    rock: 'Roca',
    bug: 'Bicho',
    ghost: 'Fantasma',
    steel: 'Acero',
    fire: 'Fuego',
    water: 'Agua',
    grass: 'Planta',
    electric: 'Eléctrico',
    psychic: 'Psíquico',
    ice: 'Hielo',
    dragon: 'Dragón',
    dark: 'Siniestro',
    fairy: 'Hada',
    shadow: 'Sombra',
};

export const generacionTraducida = {
    'generation-i': 'Generación I',
    'generation-ii': 'Generación II',
    'generation-iii': 'Generación III',
    'generation-iv': 'Generación IV',
    'generation-v': 'Generación V',
    'generation-vi': 'Generación VI',
    'generation-vii': 'Generación VII',
    'generation-viii': 'Generación VIII',
    'generation-ix': 'Generación IX',
};

export const statsTraducidas = {
    hp: 'Salud',
    attack: 'Ataque',
    defense: 'Defensa',
    'special-attack': 'Ataque Especial',
    'special-defense': 'Defensa Especial',
    speed: 'Velocidad',
};